### ISSUE TITLE
-num_res problem

### ISSUE THREAD

**Issue by subzerofun** [chuanli11/CNNMRF#18]
Hey, thanks for the code - i´m getting amazing results. i only have one problem: everytime i try a resolution greater than 3 i get this error:
qlua: ./transfer_CNNMRF_wrapper.lua:311: bad argument #3 to 'format' (number expected, got nil)
stack traceback:
	[C]: at 0x01003fae90
	[C]: in function 'format'
	./transfer_CNNMRF_wrapper.lua:311: in function 'maybe_print'
	./transfer_CNNMRF_wrapper.lua:340: in function 'opfunc'
	/Users/david/CNNMRF/mylib/myoptimizer.lua:179: in function 'mylbfgs'
	./transfer_CNNMRF_wrapper.lua:505: in function 'main'
	cnnmrf.lua:92: in main chunk

these are my options:
qlua cnnmrf.lua -num_res 4 -max_size 600 -content_name xxx -style_name xxx -type transfer -mode memory -gpu_chunck_size_1 256 -gpu_chunck_size_2 4

**Comment by Madrawn** [comment]
cmd:option('-num_iter','100,100,100', "Number of iterations for each resolution. You can use comma-separated values.") 
You have to include the num_iter for the 4th resolution.

But I found another problem.
While I'm using the run_trans.lua I also get an error when I run with a num_res bigger than 3.  Those are my parameters: {'pic', 'psy4', 'image', 384, 4, {500, 100, 100, 50}, {12, 21}, {1e-4, 1e-4}, {3, 3}, 1, 1, {2, 2}, {2, 2}, {0, 0}, {23}, 2e1, 1e-3, 'speed', 256, 16, 'cudnn'},

The problem here seems to be that for small image sizes the helper function "computeBB" rounds either "min_x" or "min_y" down to 0, which later causes a array out of bounds error in "transfer_CNNMRF_wrapper.lua->build_mrf(id_mrf)". I fixed it for myself by correcting the 0's to 1's if it happens, but I have no clue if that is actually correct in the long run.

But I'm posting this anyways, in case someone else runs into that.

**Comment by chuanli11** [comment]
@Madrawn Thanks a lot for pointing out the rounding issue. I will fix it in the next push as you suggested.
